### ISSUE TITLE
Pre-workshop checklist

### ISSUE THREAD

**Issue by olexandr-konovalov** [StAResComp/2019-09-23-standrews#6]
* Workshop page
- [ ] update location (add room number)
- [ ] update the list of instructors
- [ ] update the list of helpers
- [ ] update schedule: who teaches what and when
- [ ] create etherpads (one per room) and put links

* Logistics
- [ ] fill in workshop request form on the Carpentries website 
- [ ] reminder to fill in the pre-workshop survey
- [ ] reminder to install software in advance (also, we will be able to help on the spot from 9am before the start of the workshop)
- [ ] organise drop-in sessions to help with installation
- [ ] reminder about configuring wi-fi 
- [ ] get link to the results of pre-workshop survey
- [ ] order refreshment breaks and lunches
- [ ] put door signs

* Equipment
- [ ] 2 additional projectors
- [ ] borrowed laptops
- [ ] extension cables
- [ ] arrange tables
- [ ] spare w-fi guest logins
- [ ] stickies
- [ ] print door signs
- [ ] blue-tack for door signs
- [ ] whiteboard markers
- [ ] Windows virtual machine

**Comment by olexandr-konovalov** [comment]
@pgmccann @peterjc I've entered my feedback from stickies at https://github.com/StAResComp/2019-09-23-standrews/wiki

**Comment by peterjc** [comment]
Cross reference #7 for sticky note feedback
